version: "3"
services:

  auth-db:
    image: postgres
    container_name: auth-db
    restart: always
    environment:
      - POSTGRES_DB=auth-db
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=teste
    ports:
      - 5432:5432


  product-db:
    image: postgres
    container_name: product-db
    restart: always
    environment:
      - POSTGRES_DB=product-db
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=teste
    ports:
      - 5433:5432


  sales-db:
    image: tutum/mongodb
    container_name: sales-db
    restart: always
    environment:
      - MONGODB_DATABASE=auth-db
      - MONGODB_USER=admin
      - MONGODB_PASS=teste
    ports:
      - 27017:27017
      - 28017:28017

  sales-rabit:
    image: rabbitmq:3-management
    container_name: sales-rabit
    restart: always
    ports:
      - 5672:5672
      - 25672:25672
      - 15672:15672

